FROM almalinux:9
ENTRYPOINT [ "ping"]
CMD ["google.com"]

## You can run docker run -d <imagename>  ==> it will ping google by default
## To ping facebook give, docker run -d <imagename> facebook.com
 ## as entrypoint will append the value in CMD or command passed in CLI
